{
 "title": "Health",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "heartrate",
     "select": [
      [
       { "params": [ "bpm" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "hrv_balance",
     "measurement": "daily_readiness_contributors",
     "select": [
      [
       { "params": [ "hrv_balance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Calorie burn",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "daily_activity",
     "select": [
      [
       { "params": [ "total_calories" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stress score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "daily_stress",
     "select": [
      [
       { "params": [ "stress_high" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "daily_sleep",
     "select": [
      [
       { "params": [ "score" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Body stats",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "fat %",
     "measurement": "scale_metrics",
     "select": [
      [
       { "params": [ "fat" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "muscle %",
     "measurement": "scale_metrics",
     "select": [
      [
       { "params": [ "muscle" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "water %",
     "measurement": "scale_metrics",
     "select": [
      [
       { "params": [ "weight" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Body stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "weights (lbs)",
     "measurement": "scale_metrics",
     "select": [
      [
       { "params": [ "weight" ], "type": "field" },
       { "params": [ " *2.20462" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}